basePath: /api/v1
definitions:
  model.CreateAccount:
    properties:
      balance:
        type: number
      pin:
        type: string
      type:
        type: string
    type: object
host: 127.0.0.1:3200
info:
  contact:
    email: nukie.nxk@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Account service API documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Account Service
  version: "1.0"
paths:
  /account/:
    get:
      consumes:
      - application/json
      description: Get all account
      produces:
      - application/json
      responses: {}
      summary: Get all account
      tags:
      - account
    post:
      consumes:
      - application/json
      description: Create account
      parameters:
      - description: Account information
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/model.CreateAccount'
      produces:
      - application/json
      responses: {}
      summary: Create account
      tags:
      - account
  /account/{id}:
    get:
      consumes:
      - application/json
      description: Get account by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get account by ID
      tags:
      - account
swagger: "2.0"
