basePath: /api/v1
definitions:
  model.ChangePinRequest:
    properties:
      id:
        type: string
      new_pin:
        type: string
      old_pin:
        type: string
    required:
    - id
    - new_pin
    - old_pin
    type: object
  model.CreateAccount:
    properties:
      balance:
        type: number
      pin:
        type: string
      type:
        type: string
    type: object
  model.DeleteAccount:
    properties:
      id:
        type: string
      pin:
        type: string
    type: object
  model.TopUp:
    properties:
      amount:
        type: number
      id:
        type: string
    type: object
host: 127.0.0.1:3200
info:
  contact:
    email: nukie.nxk@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Account service API documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Account Service
  version: "1.0"
paths:
  /account/:
    get:
      consumes:
      - application/json
      description: Get all account
      produces:
      - application/json
      responses: {}
      summary: Get all account
      tags:
      - account
    post:
      consumes:
      - application/json
      description: Create account
      parameters:
      - description: Account information
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/model.CreateAccount'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: Create account
      tags:
      - account
  /account/{id}:
    get:
      consumes:
      - application/json
      description: Get account by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get account by ID
      tags:
      - account
  /account/change-pin:
    put:
      consumes:
      - application/json
      description: Change the PIN of the account
      parameters:
      - description: Change PIN request
        in: body
        name: changePin
        required: true
        schema:
          $ref: '#/definitions/model.ChangePinRequest'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: Change account PIN
      tags:
      - account
  /account/delete:
    delete:
      consumes:
      - application/json
      description: Delete account by verifying ID and PIN
      parameters:
      - description: Delete account information
        in: body
        name: deleteAccount
        required: true
        schema:
          $ref: '#/definitions/model.DeleteAccount'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: Delete account
      tags:
      - account
  /account/topup:
    post:
      consumes:
      - application/json
      description: Top up account
      parameters:
      - description: Top up information
        in: body
        name: topUp
        required: true
        schema:
          $ref: '#/definitions/model.TopUp'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: Top up account
      tags:
      - account
swagger: "2.0"
