basePath: /api/v1
definitions:
  model.CreateTransaction:
    properties:
      amount:
        type: number
      destinationAccountID:
        type: string
      sourceAccountID:
        type: string
    type: object
host: 127.0.0.1:3300
info:
  contact:
    email: nukie.nxk@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Account service API documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Account Service
  version: "1.0"
paths:
  /transaction/:
    get:
      consumes:
      - application/json
      description: Get all transaction
      produces:
      - application/json
      responses: {}
      summary: Get all transaction
      tags:
      - transaction
    post:
      consumes:
      - application/json
      description: Create transaction
      parameters:
      - description: Transaction information
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/model.CreateTransaction'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: Create transaction
      tags:
      - transaction
  /transaction/{id}:
    get:
      consumes:
      - application/json
      description: Get transaction by ID
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get transaction by ID
      tags:
      - transaction
swagger: "2.0"
