name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22', '1.23']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Create ENV file
        run: |
          mkdir -p env
          echo "DB_COMPUTE_ID=${{ secrets.DB_COMPUTE_ID }}" > env/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> env/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> env/.env
          echo "AUTH_COMPUTE_ID=${{ secrets.AUTH_COMPUTE_ID }}" >> env/.env
          echo "AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }}" >> env/.env
          echo "AUTH_NAME=${{ secrets.AUTH_NAME }}" >> env/.env
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> env/.env
          echo "ACCOUNT_NAME=${{ secrets.ACCOUNT_NAME }}" >> env/.env
          echo "TRANSACTION_NAME=${{ secrets.TRANSACTION_NAME }}" >> env/.env
          echo "PAYMENT_NAME=${{ secrets.PAYMENT_NAME }}" >> env/.env
      
      - name: Display Go version
        run: go version

      - name: Go mod tidy
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Compose Build
        run: |
          docker compose up --build
          docker compose ps
          docker compose down